server:
  port: 8888
spring:
  application:
    name: msa-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/blangka/msa-config.git

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka